import math

""" File with constants for voice separation """

MAX_VOICES = 4

# VERTICAL COSTS
VOICE_CROSSING_COST = 1000
DIFFERENT_LENGTH_COST = math.inf
TONAL_FUSION_COST = math.inf
CHORD_WIDTH_COST = math.inf

# HORIZONTAL COSTS
REST_COST = 11
OVERLAP_COST = math.inf
DURATION_COST = 12
LEAP_COST = 15
DISTANCE_COST = 13 

# OTHER COSTS
NEW_VOICE_COST = 10
EMPTY_VOICE_COST = 10



